name: Build and push docker image

on: 
  push:
    branches:
      - main
env: 
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: fcaj-bookshop-ecr
  ECR_REGISTRY: ${{ inputs.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com
  AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        oidc-token: ${{ secrets.AWS_OIDC_TOKEN }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GithubActionsRole
    
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and push docker image
      run: |
        docker build -t ${{ env.ECR_REPOSITORY }}:latest . \
        ./backend
        docker tag ${{ env.ECR_REPOSITORY }}:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
        echo "Build and push completed successfully!"


    